

services:
  webserver:
    image: "moodlehq/moodle-php-apache:8.2"
    depends_on:
      - db
      - mailpit
    volumes:
      - "./moodle:/var/www/html"
      - "./assets/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/moodle-faildump.conf"
      - "./assets/web/apache2_mailpit.conf:/etc/apache2/conf-enabled/apache2_mailpit.conf"
    environment:
      MOODLE_DOCKER_RUNNING: "1"
      MOODLE_DOCKER_DBNAME: "moodle"
      MOODLE_DOCKER_DBUSER: "moodle"
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: "firefox"
      MOODLE_DOCKER_WEB_HOST: "localhost"
      MOODLE_DOCKER_TIMEOUT_FACTOR: "1"
      MOODLE_DOCKER_DBTYPE: "pgsql"
      MOODLE_DOCKER_WEB_PORT: "8000"
    ports:
      - "8000:80"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: "moodle"
      POSTGRES_PASSWORD: "m@0dl3ing"
      POSTGRES_DB: "moodle"

  mailpit:
    image: axllent/mailpit:v1.10
    environment:
      MP_WEBROOT: /_/mail/

  exttests:
    image: moodlehq/moodle-exttests
    volumes:
      - "./assets/exttests/apache2_ports.conf:/etc/apache2/ports.conf"
      - "./assets/exttests/apache2.conf:/etc/apache2/sites-enabled/000-default.conf"

  selenium:
    image: "selenium/standalone-firefox:4"
    volumes:
      - "./moodle:/var/www/html:ro"
